[parity]
chain = "spec.json"
base_path = "data"

[account]
unlock = ["0xc08c3def622af1476f2db0e3cc8ccaead07be3bb"]
password = ["node.pwd"]

[mining]
usd_per_tx = "0"
force_sealing = true
engine_signer = "0xc08c3def622af1476f2db0e3cc8ccaead07be3bb"
gas_floor_target = "6700000"
reseal_on_txs = "none"
min_gas_price = 0

[rpc]
interface = "0.0.0.0"
cors = ["all"]
hosts = ["all"]
# apis = ["web3", "eth", "parity", "parity_set", "net", "traces", "rpc"]
apis = ["web3", "eth", "net", "pubsub", "parity_pubsub", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[websockets]
disable = false
port = 8546
interface = "all"
origins = ["all"]
apis = ["web3", "eth", "net", "pubsub", "parity_pubsub", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]
hosts = ["all"]

[misc]
log_file = "parity.log"
